spring:
  banner:
    location: classpath:banner/banner-local.txt

  datasource:
    url: jdbc:log4jdbc:sqlserver://localhost:1433;DatabaseName=storedb
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: devops
    password: new1234@
