server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /econtract
  tomcat:
    max-swallow-size: -1

logging:
  config: classpath:logback/logback-spring.xml

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  profiles:
    active: local # default profile
  banner:
    location: classpath:banner/banner.txt
  messages:
    basename: i18n/messages
    encoding: UTF-8
  thymeleaf:
    cache: false

# Mybatis Config
mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/**/*.xml
    
    

  